# Generated by Django 4.2.7 on 2024-01-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_project_project_cover_alter_picture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='link_demo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
